<a href="https://colab.research.google.com/github/abhiram-9396/DSA5720/blob/main/700765899_ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Abhiram Gatreddi

700765899


1.Create a class Employee and then do the following:

• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [ ]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Abhi Ram", "Gatreddi", 100000, "Manager")
employee2 = Employee("Karthik", "Gatreddi", 60000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Jaya", "Balreddi", 74000, "Finance")
fulltime_employee2 = FulltimeEmployee("Vijay", "Gatreddi", 70000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)


Average Salary for Employees: 40000.0
Average Salary for Fulltime Employees: 36000.0


2.Numpy

Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)

In [ ]:
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [ 9.97556936 15.32163579 13.77592668 11.00004898 11.36784475  3.73792275
  8.14324857 10.99153246 18.07593325  5.18201545 19.2082749   2.98674153
  3.80923964 17.38576262  3.0465521  14.97816108 19.93126753 14.90884757
 14.44902489 15.33674488]


In [ ]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[ 9.97556936 15.32163579 13.77592668 11.00004898 11.36784475]
 [ 3.73792275  8.14324857 10.99153246 18.07593325  5.18201545]
 [19.2082749   2.98674153  3.80923964 17.38576262  3.0465521 ]
 [14.97816108 19.93126753 14.90884757 14.44902489 15.33674488]]


In [ ]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 9.97556936  0.         13.77592668 11.00004898 11.36784475]
 [ 3.73792275  8.14324857 10.99153246  0.          5.18201545]
 [ 0.          2.98674153  3.80923964 17.38576262  3.0465521 ]
 [14.97816108  0.         14.90884757 14.44902489 15.33674488]]


Loom Video Link

https://www.loom.com/share/6e43ec648ea54c5799e528b4ece389bd?sid=c6a708d9-2f96-4c0d-b479-8e28b8157940